# Generated by Django 5.2.15 on 2026-07-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth2_provider", "0016_alter_devicegrant_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="dcr_created",
            field=models.BooleanField(
                default=False,
                help_text="True if this application was registered via Dynamic Client Registration (RFC 7591)",
            ),
        ),
    ]
