# Generated by Django 5.2.15 on 2026-07-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0012_alter_sampledevicegrant_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="basetestapplication",
            name="dcr_created",
            field=models.BooleanField(
                default=False,
                help_text="True if this application was registered via Dynamic Client Registration (RFC 7591)",
            ),
        ),
        migrations.AddField(
            model_name="sampleapplication",
            name="dcr_created",
            field=models.BooleanField(
                default=False,
                help_text="True if this application was registered via Dynamic Client Registration (RFC 7591)",
            ),
        ),
    ]
